[build]
  command = "yarn build"
  publish = ".next"   

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; img-src * data: blob: 'unsafe-inline'; connect-src * 'unsafe-inline'; frame-src *; upgrade-insecure-requests;"

[[redirects]]
  from = "/api/*"
  to = "http://13.125.177.110:8080/api/:splat"
  status = 200
  force = true