[build]
  command = "yarn build"
  publish = ".next"   

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"

[[redirects]]
  from = "/api/*"
  to = "http://13.125.177.110:8080/api/:splat"
  status = 200
  force = true