import "./globals.css";

import { dehydrate, QueryClient } from "@tanstack/react-query";
import type { Metadata } from "next";

import NavBar from "@/components/nav-bar";
import AuthInitializer from "@/provider/AuthInitializer";

import Providers from "./provider";

export const metadata: Metadata = {
  title: "Online-Investment-Platform",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="ko">
      <body className="flex">
        <Providers dehydratedState={dehydratedState}>
          <AuthInitializer />
          <NavBar />
          <main className="ml-82 flex-1">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
