import "./globals.css";

import type { Metadata } from "next";

import NavBar from "@/components/nav-bar";
import AuthInitializer from "@/provider/AuthInitializer";

export const metadata: Metadata = {
  title: "Online-Investment-Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="flex">
        <AuthInitializer />
        <NavBar />
        <main className="ml-82 flex-1">{children}</main>
      </body>
    </html>
  );
}
